version: "3.9"

services:
  app:
    image: wikilinks
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      APP_ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18080:8080"
